"""Embedding generation service using sentence-transformers."""

import logging
from typing import List, Optional

from sentence_transformers import SentenceTransformer

from app.config import settings

logger = logging.getLogger(__name__)


class EmbeddingService:
    """Service for generating text embeddings using sentence-transformers."""

    def __init__(self, model_name: Optional[str] = None):
        """
        Initialize embedding service with model.

        Args:
            model_name: Name of the sentence-transformers model (defaults to settings)
        """
        self.model_name = model_name or settings.embedding_model
        self.model: Optional[SentenceTransformer] = None
        self._load_model()

    def _load_model(self):
        """Load the sentence-transformers model."""
        try:
            logger.info(f"Loading embedding model: {self.model_name}")
            self.model = SentenceTransformer(self.model_name)
            logger.info(f"Model {self.model_name} loaded successfully")
        except Exception as e:
            logger.error(f"Failed to load embedding model {self.model_name}: {str(e)}")
            raise RuntimeError(
                f"Could not load embedding model {self.model_name}. "
                f"Please ensure sentence-transformers is installed correctly. Error: {str(e)}"
            )

    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.

        Args:
            text: Text to generate embedding for

        Returns:
            List of floats representing the embedding vector

        Raises:
            RuntimeError: If model is not loaded
            ValueError: If text is empty
        """
        if not self.model:
            raise RuntimeError("Embedding model is not loaded")

        if not text or not text.strip():
            raise ValueError("Text cannot be empty")

        try:
            # Generate embedding
            embedding = self.model.encode(
                text,
                convert_to_numpy=True,
                normalize_embeddings=True,
            )

            # Convert numpy array to list
            return embedding.tolist()
        except Exception as e:
            logger.error(f"Error generating embedding: {str(e)}")
            raise RuntimeError(f"Failed to generate embedding: {str(e)}")

    def generate_embeddings_batch(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple texts (batch processing).

        More efficient than calling generate_embedding() multiple times.

        Args:
            texts: List of texts to generate embeddings for

        Returns:
            List of embedding vectors (each is a list of floats)

        Raises:
            RuntimeError: If model is not loaded
            ValueError: If texts list is empty
        """
        if not self.model:
            raise RuntimeError("Embedding model is not loaded")

        if not texts:
            raise ValueError("Texts list cannot be empty")

        # Filter out empty texts
        valid_texts = [text for text in texts if text and text.strip()]
        if not valid_texts:
            raise ValueError("No valid texts to embed")

        try:
            # Generate embeddings in batch
            embeddings = self.model.encode(
                valid_texts,
                convert_to_numpy=True,
                normalize_embeddings=True,
                show_progress_bar=False,
                batch_size=32,  # Process in batches of 32
            )

            # Convert numpy array to list of lists
            return embeddings.tolist()
        except Exception as e:
            logger.error(f"Error generating batch embeddings: {str(e)}")
            raise RuntimeError(f"Failed to generate batch embeddings: {str(e)}")

    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by this model.

        Returns:
            Embedding dimension (e.g., 384 for all-MiniLM-L6-v2)
        """
        if not self.model:
            return settings.embedding_dimension

        # Get dimension from model
        try:
            # Create a dummy embedding to get dimension
            test_embedding = self.model.encode("test", convert_to_numpy=True)
            return test_embedding.shape[0]
        except Exception:
            # Fallback to config value
            return settings.embedding_dimension
