"""Vector database service using ChromaDB."""

import logging
from typing import List, Dict, Any, Optional

import chromadb
from chromadb.config import Settings as ChromaSettings

from app.config import settings

logger = logging.getLogger(__name__)


class VectorStore:
    """Service for managing document chunks in ChromaDB vector database."""

    def __init__(self):
        """Initialize ChromaDB client and collection."""
        self.client: Optional[chromadb.ClientAPI] = None
        self.collection: Optional[chromadb.Collection] = None
        self._initialize_client()

    def _initialize_client(self):
        """Initialize ChromaDB client and get/create collection."""
        try:
            # Create persistent ChromaDB client
            self.client = chromadb.PersistentClient(
                path=str(settings.chroma_db_path),
                settings=ChromaSettings(
                    anonymized_telemetry=False,
                    allow_reset=True,
                ),
            )

            # Get or create collection with cosine distance metric
            # Since embeddings are normalized, cosine distance is appropriate
            self.collection = self.client.get_or_create_collection(
                name=settings.chroma_collection_name,
                metadata={"description": "Document chunks with embeddings"},
                # Use cosine distance for normalized embeddings
                # This ensures similarity scores are in the range [0, 1]
            )
            
            # Log collection stats for debugging
            try:
                all_chunks = self.collection.get()
                num_chunks = len(all_chunks["ids"]) if all_chunks["ids"] else 0
                logger.debug(f"ChromaDB collection '{settings.chroma_collection_name}' contains {num_chunks} chunks")
            except Exception as e:
                logger.warning(f"Could not count chunks in collection: {str(e)}")

            logger.info(
                f"ChromaDB initialized: collection '{settings.chroma_collection_name}' "
                f"at path '{settings.chroma_db_path}'"
            )
        except Exception as e:
            logger.error(f"Failed to initialize ChromaDB: {str(e)}")
            raise RuntimeError(f"Could not initialize ChromaDB: {str(e)}")

    def add_document_chunks(
        self,
        document_id: str,
        chunks: List[Dict[str, Any]],
    ) -> List[str]:
        """
        Add document chunks with embeddings to ChromaDB.

        Args:
            document_id: Document identifier
            chunks: List of chunk dictionaries, each containing:
                - text: Chunk text content
                - embedding: Embedding vector (list of floats)
                - chunk_index: Chunk index within document
                - filename: Original filename
                - start_char: Starting character position
                - end_char: Ending character position

        Returns:
            List of chunk IDs (generated by ChromaDB)

        Raises:
            RuntimeError: If ChromaDB is not initialized
            ValueError: If chunks list is empty or missing required fields
        """
        if not self.collection:
            raise RuntimeError("ChromaDB collection is not initialized")

        if not chunks:
            raise ValueError("Chunks list cannot be empty")

        # Prepare data for ChromaDB
        ids = []
        embeddings = []
        documents = []
        metadatas = []

        for chunk in chunks:
            # Validate required fields
            if "text" not in chunk:
                raise ValueError("Chunk must contain 'text' field")
            if "embedding" not in chunk:
                raise ValueError("Chunk must contain 'embedding' field")

            # Generate unique chunk ID
            chunk_id = f"{document_id}_chunk_{chunk.get('chunk_index', len(ids))}"
            ids.append(chunk_id)

            # Extract embedding
            embedding = chunk["embedding"]
            if not isinstance(embedding, list):
                raise ValueError("Embedding must be a list of floats")
            embeddings.append(embedding)

            # Extract text
            documents.append(chunk["text"])

            # Prepare metadata (ChromaDB requires string values for metadata)
            metadata = {
                "document_id": document_id,
                "filename": str(chunk.get("filename", "")),
                "chunk_index": str(chunk.get("chunk_index", "")),
                "start_char": str(chunk.get("start_char", "")),
                "end_char": str(chunk.get("end_char", "")),
            }
            metadatas.append(metadata)

        try:
            # Add to ChromaDB collection
            self.collection.add(
                ids=ids,
                embeddings=embeddings,
                documents=documents,
                metadatas=metadatas,
            )

            logger.info(
                f"Added {len(ids)} chunks for document {document_id} to ChromaDB"
            )
            return ids
        except Exception as e:
            logger.error(f"Failed to add chunks to ChromaDB: {str(e)}")
            raise RuntimeError(f"Could not store chunks in ChromaDB: {str(e)}")

    def search(
        self,
        query_embedding: List[float],
        top_k: int = None,
        similarity_threshold: float = None,
        document_id: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """
        Search for similar chunks using query embedding.

        Args:
            query_embedding: Query embedding vector
            top_k: Number of top results to return (defaults to settings.top_k)
            similarity_threshold: Minimum similarity score (defaults to settings.similarity_threshold)
            document_id: Optional filter by document ID

        Returns:
            List of result dictionaries, each containing:
                - id: Chunk ID
                - text: Chunk text
                - metadata: Chunk metadata
                - distance: Similarity distance (lower is more similar)
                - score: Similarity score (higher is more similar, 1 - distance)

        Raises:
            RuntimeError: If ChromaDB is not initialized
        """
        if not self.collection:
            raise RuntimeError("ChromaDB collection is not initialized")

        top_k = top_k or settings.top_k
        similarity_threshold = similarity_threshold or settings.similarity_threshold

        # Build where clause if filtering by document_id
        where_clause = None
        if document_id:
            where_clause = {"document_id": document_id}

        try:
            logger.debug(
                f"Searching ChromaDB: top_k={top_k}, threshold={similarity_threshold}, "
                f"collection='{self.collection.name if self.collection else 'None'}'"
            )
            
            # Search in ChromaDB
            results = self.collection.query(
                query_embeddings=[query_embedding],
                n_results=top_k,
                where=where_clause,
            )
            
            # Log query results for debugging
            num_raw_results = len(results["ids"][0]) if results["ids"] and results["ids"][0] else 0
            logger.debug(f"ChromaDB query returned {num_raw_results} raw results")

            # Process results
            search_results = []
            if results["ids"] and len(results["ids"][0]) > 0:
                for i in range(len(results["ids"][0])):
                    # ChromaDB returns distances (lower is better)
                    distance = results["distances"][0][i] if results["distances"] else 1.0
                    
                    # Convert distance to similarity score
                    # For normalized embeddings, ChromaDB may use L2 or cosine distance
                    # If L2 distance: cosine_similarity = 1 - (l2_distance^2 / 2) for normalized vectors
                    # If cosine distance: cosine_similarity = 1 - distance
                    # Since embeddings are normalized, we can use: similarity = 1 - (distance^2 / 2)
                    # But to be safe, check if distance > 1 (L2) or <= 1 (cosine)
                    if distance > 1.0:
                        # L2 distance for normalized vectors: convert to cosine similarity
                        # For normalized vectors: l2_dist^2 = 2 * (1 - cosine_sim)
                        # So: cosine_sim = 1 - (l2_dist^2 / 2)
                        score = max(0.0, 1.0 - (distance ** 2 / 2.0))
                    else:
                        # Cosine distance: similarity = 1 - distance
                        score = 1.0 - distance

                    # Only include results above threshold
                    if score >= similarity_threshold:
                        search_results.append(
                            {
                                "id": results["ids"][0][i],
                                "text": results["documents"][0][i] if results["documents"] else "",
                                "metadata": results["metadatas"][0][i] if results["metadatas"] else {},
                                "distance": distance,
                                "score": score,
                            }
                        )
                    else:
                        logger.debug(
                            f"Result filtered out by threshold: score={score:.3f}, "
                            f"threshold={similarity_threshold}, distance={distance:.3f}"
                        )

            logger.info(
                f"Search returned {len(search_results)} results (threshold: {similarity_threshold})"
            )
            return search_results
        except Exception as e:
            logger.error(f"Failed to search ChromaDB: {str(e)}")
            raise RuntimeError(f"Could not search ChromaDB: {str(e)}")

    def delete_document(self, document_id: str) -> int:
        """
        Delete all chunks for a document from ChromaDB.

        Args:
            document_id: Document identifier

        Returns:
            Number of chunks deleted

        Raises:
            RuntimeError: If ChromaDB is not initialized
        """
        if not self.collection:
            raise RuntimeError("ChromaDB collection is not initialized")

        try:
            # Get all chunks for this document
            results = self.collection.get(
                where={"document_id": document_id},
            )

            if not results["ids"]:
                logger.info(f"No chunks found for document {document_id}")
                return 0

            # Delete chunks
            self.collection.delete(ids=results["ids"])

            num_deleted = len(results["ids"])
            logger.info(f"Deleted {num_deleted} chunks for document {document_id}")
            return num_deleted
        except Exception as e:
            logger.error(f"Failed to delete document from ChromaDB: {str(e)}")
            raise RuntimeError(f"Could not delete document from ChromaDB: {str(e)}")

    def get_document_chunks(
        self,
        document_id: str,
        limit: int = None,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve representative chunks from a specific document (bypasses similarity search).
        Uses smart sampling: evenly distributed chunks from beginning, middle, and end.
        Useful as fallback when semantic search returns no results for document-scoped queries.

        Args:
            document_id: Document identifier
            limit: Maximum number of chunks to retrieve (defaults to settings.top_k)

        Returns:
            List of chunk dictionaries with text and metadata (same format as search results)

        Raises:
            RuntimeError: If ChromaDB is not initialized
        """
        if not self.collection:
            raise RuntimeError("ChromaDB collection is not initialized")

        limit = limit or settings.top_k

        try:
            # Get all chunks from the document to count them
            all_results = self.collection.get(
                where={"document_id": document_id},
            )

            if not all_results["ids"]:
                logger.info(f"No chunks found for document {document_id}")
                return []

            total_chunks = len(all_results["ids"])

            # If we have fewer chunks than limit, return all
            if total_chunks <= limit:
                # Return all chunks in order
                selected_indices = list(range(total_chunks))
            else:
                # Sample evenly across the document
                # Strategy: Get chunks from beginning, middle, and end
                selected_indices = []

                # Beginning (first chunk)
                selected_indices.append(0)

                # Middle chunks (evenly distributed)
                middle_count = limit - 2  # Reserve one for beginning, one for end
                if middle_count > 0:
                    step = max(1, (total_chunks - 2) // middle_count)
                    for i in range(1, total_chunks - 1, step):
                        if len(selected_indices) < limit - 1:  # Reserve last for end
                            selected_indices.append(i)

                # End (last chunk)
                if len(selected_indices) < limit:
                    selected_indices.append(total_chunks - 1)

                # Remove duplicates and sort, then limit
                selected_indices = sorted(list(set(selected_indices)))[:limit]

            # Build results with selected indices (same format as search results)
            chunks = []
            for idx in selected_indices:
                chunks.append({
                    "id": all_results["ids"][idx],
                    "text": all_results["documents"][idx] if all_results["documents"] else "",
                    "metadata": all_results["metadatas"][idx] if all_results["metadatas"] else {},
                    "distance": 0.0,  # No distance for direct retrieval
                    "score": 1.0,  # Maximum score since we're retrieving from the document
                })

            logger.info(
                f"Retrieved {len(chunks)} representative chunks from document {document_id} "
                f"(sampled from {total_chunks} total chunks)"
            )
            return chunks
        except Exception as e:
            logger.error(f"Failed to retrieve chunks from document {document_id}: {str(e)}")
            raise RuntimeError(f"Could not retrieve chunks from document {document_id}: {str(e)}")
